'use client';

import Header from '@/components/Header';
import DisclaimerBanner from '@/components/DisclaimerBanner';
import Footer from '@/components/Footer';

export default function MethodPage() {
  return (
    <>
      <Header activeFilter="all" onFilterChange={() => {}} />
      <DisclaimerBanner />
      <main className="main-content">
        <div className="story-detail">
          <h1 className="static-page-title">How AI Speculation Works</h1>

          <p>
            Every piece of analysis on NewsReal.ai is generated by large language models.
            Here&rsquo;s exactly how the pipeline works — no black boxes.
          </p>

          <h2>1. Ingestion</h2>
          <p>
            We pull stories from a curated set of news sources across the political spectrum.
            Each story enters our pipeline with its raw headline, source attribution, and
            publication metadata.
          </p>

          <h2>2. Classification</h2>
          <p>
            A fast AI model classifies each story by category, assigns preliminary bias tags,
            and scores the headline for manipulation techniques (emotional language, false
            framing, missing context). This is the triage layer — quick, cheap, and designed
            to prioritize which stories deserve deeper analysis.
          </p>

          <h2>3. Deep Analysis</h2>
          <p>
            Stories that surface to the main feed get a full analysis pass from a more capable
            model. This includes: bias framing from multiple political perspectives, financial
            connection mapping (who benefits, who&rsquo;s paying), historical pattern matching,
            and identification of what&rsquo;s being left out of the mainstream narrative.
          </p>

          <h2>4. Cross-Referencing</h2>
          <p>
            We look for coordinated narratives — when multiple outlets push the same framing
            simultaneously, that&rsquo;s a signal worth flagging. We also cross-reference
            story timing against government filings, contract awards, and regulatory actions
            to surface potential obfuscation patterns.
          </p>

          <h2>5. Presentation</h2>
          <p>
            Every analysis block on the site is labeled as AI-generated speculation. The
            manipulation scores, bias tags, and financial connections are all model outputs,
            not editorial judgments. We show our work so you can evaluate the analysis on
            its merits.
          </p>

          <h2>The Limitations</h2>
          <p>
            AI models hallucinate. They get things wrong. They can be confidently incorrect
            about specific dollar amounts, dates, and relationships. Our analysis is a
            starting point for your own investigation, not an endpoint. If something we
            flag sounds important, verify it with primary sources before drawing conclusions.
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
