import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="site-footer">
      <div className="footer-disclaimer">
        <strong>{'\u26A0'} FULL DISCLOSURE:</strong> NewsReal.ai is an AI-powered entertainment
        and media criticism platform. All &ldquo;deep analysis,&rdquo; conspiracy speculation, and
        bias ratings are generated by artificial intelligence and should not be treated as factual
        reporting. We exist to make you <em>think</em> about the news you consume &mdash; not to
        replace it. Always verify with primary sources.
      </div>
      <div className="footer-links">
        <Link href="/about">About</Link>
        <Link href="/method">How AI Speculation Works</Link>
        <Link href="/bias-ratings">Bias Rating System</Link>
        <Link href="/contact">Contact</Link>
      </div>
    </footer>
  );
}
